### ISSUE TITLE
adjust naming of temp files

### ISSUE THREAD

**Issue by lheisler** [oicr-gsi/xenoclassify#2]
The temp files created by xenoclassify are simply 
human_primary.bam
human_secondary.bam
mouse_primary.bam
mouse_secondary.bam

1. these should signify host/graft, not human/mouse to be consistent with the rest of the program
2. the names are the same for each run, such that to run this across many files, the results must be saved in a distinct folder.  Names should either use the provided prefix, or use a temp string

**Comment by pruzanov** [comment]
fixed
